// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxnkfaxfucmsujgudsxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4bmtmYXhmdWNtc3VqZ3Vkc3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjY3NDQsImV4cCI6MjA2Mzc0Mjc0NH0.6uvbqH3bqaH3iCXZ8CCAYJsIuaXhHpmyHzBx7mwPMJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);